export type ExpertDomain = {
    fr: string;
    en: string;
    ar: string;
};

export const EXPERT_DOMAINS: ExpertDomain[] = [
    {
        fr: 'Administration Et Gouvernance Publiques',
        en: 'Public Administration and Governance',
        ar: 'الإدارة والحكامة العمومية',
    },
    {
        fr: 'Achats Responsables & Performants',
        en: 'Responsible and Efficient Procurement',
        ar: 'المشتريات المسؤولة والفعالة',
    },
    {
        fr: "Activités Sportives d'Aventures",
        en: 'Adventure Sports Activities',
        ar: 'أنشطة الرياضات المغامِرة',
    },
    {
        fr: 'Administration publique',
        en: 'Public Administration',
        ar: 'الإدارة العمومية',
    },
    {
        fr: 'Affaires réglementaires scientifiques',
        en: 'Scientific Regulatory Affairs',
        ar: 'الشؤون التنظيمية العلمية',
    },
    { fr: 'Agriculture', en: 'Agriculture', ar: 'الزراعة' },
    {
        fr: 'Agriculture biologique',
        en: 'Organic Agriculture',
        ar: 'الزراعة العضوية',
    },
    { fr: 'Agronomie', en: 'Agronomy', ar: 'علم الزراعة' },
    { fr: 'Agroéconomie', en: 'Agroeconomics', ar: 'الاقتصاد الزراعي' },
    { fr: 'Alphabétisation', en: 'Literacy', ar: 'محو الأمية' },
    { fr: 'Alpinisme', en: 'Mountaineering', ar: 'تسلق الجبال' },
    {
        fr: 'Amélioration des processus par la qualité',
        en: 'Process Improvement through Quality',
        ar: 'تحسين العمليات عبر الجودة',
    },
    {
        fr: 'Amélioration process',
        en: 'Process Improvement',
        ar: 'تحسين العمليات',
    },
    {
        fr: 'Analyse Prédictive des données',
        en: 'Predictive Data Analysis',
        ar: 'التحليل التنبؤي للبيانات',
    },
    {
        fr: 'Angiologue, Phlébologue, traitement des varices',
        en: 'Angiologist/Phlebologist, Varicose Veins Treatment',
        ar: 'اختصاصي أوعية دموية/أوردة، علاج الدوالي',
    },
    {
        fr: "Animation d'eenfants",
        en: "Children's Activities",
        ar: 'تنشيط الأطفال',
    },
    {
        fr: 'Antennes intelligentes pour palier à la pollution electromagnétique',
        en: 'Smart Antennas to Mitigate Electromagnetic Pollution',
        ar: 'هوائيات ذكية للحد من التلوث الكهرومغناطيسي',
    },
    { fr: 'Architecture ', en: 'Architecture', ar: 'الهندسة المعمارية' },
    {
        fr: 'Architecture du Paysage',
        en: 'Landscape Architecture',
        ar: 'هندسة المناظر الطبيعية',
    },
    { fr: 'Archivage', en: 'Archiving', ar: 'الأرشفة' },
    {
        fr: 'Archivage-Gestion Electronique des Documents',
        en: 'Archiving - Electronic Document Management',
        ar: 'الأرشفة وإدارة الوثائق الإلكترونية',
    },
    { fr: 'Aromathérapie', en: 'Aromatherapy', ar: 'العلاج بالعطور' },
    { fr: 'Art culinaire', en: 'Culinary Arts', ar: 'فنون الطهي' },
    { fr: 'Art et Sciences', en: 'Art and Sciences', ar: 'الفن والعلوم' },
    { fr: 'Art-coaching', en: 'Art Coaching', ar: 'التدريب بالفن' },
    {
        fr: 'Artisanat et céramique',
        en: 'Crafts and Ceramics',
        ar: 'الحرف والخزف',
    },
    { fr: 'Artiste peintre', en: 'Painter', ar: 'فنان تشكيلي' },
    { fr: 'Arts', en: 'Arts', ar: 'الفنون' },
    { fr: 'Arts graphiques', en: 'Graphic Arts', ar: 'الفنون الغرافيكية' },
    {
        fr: 'Assistance Internationale et aide à la personne',
        en: 'International Assistance and Personal Care',
        ar: 'المساعدة الدولية ورعاية الأشخاص',
    },
    {
        fr: 'Assistance administratif et Finance',
        en: 'Administrative and Finance Assistance',
        ar: 'المساعدة الإدارية والمالية',
    },
    { fr: 'Associatif', en: 'Nonprofit Sector', ar: 'العمل الجمعوي' },
    { fr: 'Assurances', en: 'Insurance', ar: 'التأمين' },
    { fr: 'Astrophysique', en: 'Astrophysics', ar: 'الفيزياء الفلكية' },
    { fr: 'Audiovisuel ', en: 'Audiovisual', ar: 'السمعي البصري' },
    { fr: 'Audit Public', en: 'Public Audit', ar: 'التدقيق العمومي' },
    {
        fr: 'Audit commissariat aux comptes conseil',
        en: 'Statutory Audit and Advisory',
        ar: 'تدقيق قانوني واستشارات',
    },
    {
        fr: 'Audit des systèmes de Management Qualité',
        en: 'Quality Management Systems Audit',
        ar: 'تدقيق أنظمة إدارة الجودة',
    },
    {
        fr: 'Audit et Fiscalité',
        en: 'Audit and Taxation',
        ar: 'التدقيق والجباية',
    },
    { fr: 'Audit social', en: 'Social Audit', ar: 'التدقيق الاجتماعي' },
    {
        fr: 'Audit énergétique / Diagnostic Immobilier et Arbitrage ',
        en: 'Energy Audit / Real Estate Diagnostics and Arbitration',
        ar: 'تدقيق الطاقة / التشخيص العقاري والتحكيم',
    },
    { fr: 'Autisme', en: 'Autism', ar: 'التوحد' },
    { fr: 'Autisme et Art', en: 'Autism and Art', ar: 'التوحد والفن' },
    { fr: 'Automobile', en: 'Automotive', ar: 'السيارات' },
    { fr: 'Aviation', en: 'Aviation', ar: 'الطيران' },
    {
        fr: 'Banque aux particuliers',
        en: 'Retail Banking',
        ar: 'الخدمات البنكية للأفراد',
    },
    { fr: 'Banques', en: 'Banks', ar: 'البنوك' },
    { fr: 'Big Data', en: 'Big Data', ar: 'البيانات الضخمة' },
    { fr: 'Bio-industries', en: 'Bio-industries', ar: 'الصناعات الحيوية' },
    { fr: 'Biologie', en: 'Biology', ar: 'علم الأحياء' },
    { fr: 'Biothechnologie', en: 'Biotechnology', ar: 'التكنولوجيا الحيوية' },
    {
        fr: 'Bioéthique et droits humains',
        en: 'Bioethics and Human Rights',
        ar: 'أخلاقيات علم الأحياء وحقوق الإنسان',
    },
    { fr: 'Blogging', en: 'Blogging', ar: 'التدوين' },
    { fr: 'Branding', en: 'Branding', ar: 'بناء العلامة التجارية' },
    {
        fr: 'Business Process Modeling BPM',
        en: 'Business Process Modeling (BPM)',
        ar: 'نمذجة عمليات الأعمال (BPM)',
    },
    {
        fr: 'Business intelligence',
        en: 'Business Intelligence',
        ar: 'ذكاء الأعمال',
    },
    {
        fr: 'CRM & Transformation Digital',
        en: 'CRM and Digital Transformation',
        ar: 'إدارة علاقات العملاء والتحول الرقمي',
    },
    {
        fr: 'Cancer de la prostate',
        en: 'Prostate Cancer',
        ar: 'سرطان البروستاتا',
    },
    {
        fr: 'Capital investissement',
        en: 'Private Equity',
        ar: 'الاستثمار في رأس المال',
    },
    { fr: 'Caricature', en: 'Caricature', ar: 'الكاريكاتير' },
    { fr: 'Caricaturiste', en: 'Cartoonist', ar: 'رسام كاريكاتير' },
    { fr: 'Centre de appel', en: 'Call Center', ar: 'مركز اتصال' },
    { fr: 'Certification', en: 'Certification', ar: 'الاعتماد والشهادات' },
    { fr: 'Change Management', en: 'Change Management', ar: 'إدارة التغيير' },
    { fr: 'Changement Climatique', en: 'Climate Change', ar: 'التغير المناخي' },
    { fr: 'Changement climatique', en: 'Climate Change', ar: 'التغير المناخي' },
    {
        fr: 'Chirurgie digestive',
        en: 'Digestive Surgery',
        ar: 'جراحة الجهاز الهضمي',
    },
    { fr: 'Cinéma', en: 'Cinema', ar: 'السينما' },
    {
        fr: 'Classe preparatoires',
        en: 'Preparatory Classes',
        ar: 'الأقسام التحضيرية',
    },
    { fr: 'Coaching', en: 'Coaching', ar: 'التدريب' },
    {
        fr: 'Coaching de jeunes entrepreneurs',
        en: 'Coaching Young Entrepreneurs',
        ar: 'تدريب رواد الأعمال الشباب',
    },
    { fr: 'Coaching de vie', en: 'Life Coaching', ar: 'التدريب على الحياة' },
    { fr: 'Coaching des enfants', en: 'Child Coaching', ar: 'تدريب الأطفال' },
    { fr: 'Coaching parental', en: 'Parental Coaching', ar: 'تدريب الوالدين' },
    { fr: 'Code de la famille', en: 'Family Code', ar: 'مدونة الأسرة' },
    {
        fr: 'Commerce international',
        en: 'International Trade',
        ar: 'التجارة الدولية',
    },
    { fr: 'Commercial', en: 'Sales', ar: 'المبيعات' },
    { fr: 'Communication', en: 'Communication', ar: 'الاتصال' },
    {
        fr: 'Communication Commerciale / Digitale',
        en: 'Commercial and Digital Communication',
        ar: 'التواصل التجاري والرقمي',
    },
    {
        fr: 'Communication Publique',
        en: 'Public Communication',
        ar: 'الاتصال العمومي',
    },
    {
        fr: 'Communication RSE',
        en: 'CSR Communication',
        ar: 'تواصل المسؤولية الاجتماعية للشركات',
    },
    {
        fr: 'Communication d’entreprise',
        en: 'Corporate Communication',
        ar: 'التواصل المؤسسي',
    },
    {
        fr: 'Communication et relations publiques',
        en: 'Communication and Public Relations',
        ar: 'الاتصال والعلاقات العامة',
    },
    {
        fr: 'Communication et événementiel ',
        en: 'Communication and Events',
        ar: 'الاتصال وتنظيم الفعاليات',
    },
    {
        fr: 'Communication institutionnelle',
        en: 'Institutional Communication',
        ar: 'التواصل المؤسساتي',
    },
    {
        fr: 'Communication politique',
        en: 'Political Communication',
        ar: 'التواصل السياسي',
    },
    {
        fr: 'Communication santé',
        en: 'Health Communication',
        ar: 'التواصل الصحي',
    },
    {
        fr: 'Communication stratégique et de crise',
        en: 'Strategic and Crisis Communication',
        ar: 'التواصل الاستراتيجي وإدارة الأزمات',
    },
    {
        fr: 'Compliance : éthique des affaires',
        en: 'Compliance: Business Ethics',
        ar: 'الامتثال: أخلاقيات الأعمال',
    },
    { fr: 'Comptabilité ', en: 'Accounting', ar: 'المحاسبة' },
    {
        fr: 'Comptabilité internationale IFRS',
        en: 'International Accounting IFRS',
        ar: 'المحاسبة الدولية IFRS',
    },
    { fr: 'Comédie', en: 'Comedy', ar: 'الكوميديا' },
    { fr: 'Conception Florale', en: 'Floral Design', ar: 'تنسيق الزهور' },
    { fr: 'Conférences', en: 'Conferences', ar: 'المؤتمرات' },
    {
        fr: 'Conseil Juridique et Fiscal',
        en: 'Legal and Tax Advisory',
        ar: 'الاستشارة القانونية والضريبية',
    },
    {
        fr: 'Conseil en Propriete Intellectuelle',
        en: 'Intellectual Property Advisory',
        ar: 'الاستشارة في الملكية الفكرية',
    },
    {
        fr: 'Conseil en formation',
        en: 'Training Advisory',
        ar: 'الاستشارة في التكوين',
    },
    {
        fr: "Conseil et audit en systèmes d'information",
        en: 'IT Consulting and Audit',
        ar: 'الاستشارة والتدقيق في نظم المعلومات',
    },
    {
        fr: 'Conseil et développement des affaires',
        en: 'Business Consulting and Development',
        ar: 'الاستشارة وتطوير الأعمال',
    },
    {
        fr: 'Conseil juridique',
        en: 'Legal Advisory',
        ar: 'الاستشارة القانونية',
    },
    { fr: 'Consolidation de la paix', en: 'Peacebuilding', ar: 'بناء السلام' },
    { fr: 'Construction', en: 'Construction', ar: 'البناء' },
    {
        fr: 'Construction durable',
        en: 'Sustainable Construction',
        ar: 'البناء المستدام',
    },
    {
        fr: 'Construction/Genie Civil',
        en: 'Construction/Civil Engineering',
        ar: 'البناء/الهندسة المدنية',
    },
    { fr: 'Consulting', en: 'Consulting', ar: 'الاستشارة' },
    {
        fr: 'Consulting et formations',
        en: 'Consulting and Training',
        ar: 'الاستشارة والتكوين',
    },
    { fr: 'Contrôle Qualité', en: 'Quality Control', ar: 'مراقبة الجودة' },
    {
        fr: 'Contrôle de gestion',
        en: 'Management Control',
        ar: 'مراقبة التسيير',
    },
    {
        fr: 'Cosmétique naturelle artisanale',
        en: 'Handmade Natural Cosmetics',
        ar: 'مستحضرات تجميل طبيعية حرفية',
    },
    { fr: 'Credit management', en: 'Credit Management', ar: 'إدارة الائتمان' },
    { fr: 'Cryptographie', en: 'Cryptography', ar: 'التشفير' },
    { fr: 'Culture', en: 'Culture', ar: 'الثقافة' },
    { fr: 'Culture sécurité', en: 'Safety Culture', ar: 'ثقافة السلامة' },
    { fr: 'Cybersécurité', en: 'Cybersecurity', ar: 'الأمن السيبراني' },
    { fr: 'Data Mining', en: 'Data Mining', ar: 'تنقيب البيانات' },
    {
        fr: 'Data Mining, Analyse Prédictive, Intélligence Artificielle',
        en: 'Data Mining, Predictive Analysis, Artificial Intelligence',
        ar: 'تنقيب البيانات والتحليل التنبؤي والذكاء الاصطناعي',
    },
    {
        fr: 'Data Mining, Intelligence Artificielle, Analyse Prédictive des données',
        en: 'Data Mining, Artificial Intelligence, Predictive Data Analysis',
        ar: 'تنقيب البيانات والذكاء الاصطناعي والتحليل التنبؤي للبيانات',
    },
    { fr: 'Dermatologie', en: 'Dermatology', ar: 'الأمراض الجلدية' },
    { fr: 'Design', en: 'Design', ar: 'التصميم' },
    { fr: 'Design Thinking', en: 'Design Thinking', ar: 'التفكير التصميمي' },
    {
        fr: 'Dialogue Interculturel',
        en: 'Intercultural Dialogue',
        ar: 'الحوار بين الثقافات',
    },
    { fr: 'Digital', en: 'Digital', ar: 'الرقمي' },
    { fr: 'Diplomatie', en: 'Diplomacy', ar: 'الدبلوماسية' },
    {
        fr: 'Directrice générale dans multinationale',
        en: 'CEO in a Multinational',
        ar: 'مديرة عامة في شركة متعددة الجنسيات',
    },
    { fr: 'Discrimination', en: 'Discrimination', ar: 'التمييز' },
    { fr: 'Distribution', en: 'Distribution', ar: 'التوزيع' },
    { fr: 'Dossier du Sahara', en: 'Sahara Issue', ar: 'قضية الصحراء' },
    { fr: 'Droit', en: 'Law', ar: 'القانون' },
    {
        fr: 'Droit International Public',
        en: 'Public International Law',
        ar: 'القانون الدولي العام',
    },
    {
        fr: 'Droit Maritime et Aérien',
        en: 'Maritime and Air Law',
        ar: 'القانون البحري والجوي',
    },
    {
        fr: 'Droit Privé Comparé espace Afrique francophone et Commonwealth',
        en: 'Comparative Private Law in Francophone Africa and Commonwealth',
        ar: 'القانون الخاص المقارن في إفريقيا الفرنكفونية والكومنولث',
    },
    { fr: 'Droit Spatial', en: 'Space Law', ar: 'قانون الفضاء' },
    { fr: 'Droit dans les télécoms', en: 'Telecom Law', ar: 'قانون الاتصالات' },
    { fr: 'Droit de la famille', en: 'Family Law', ar: 'قانون الأسرة' },
    {
        fr: 'Droit de la femme rurale',
        en: "Rural Women's Law",
        ar: 'قانون المرأة القروية',
    },
    { fr: 'Droit des Affaires', en: 'Business Law', ar: 'قانون الأعمال' },
    {
        fr: "Droit des Telecoms et de l'Informatique",
        en: 'Telecom and IT Law',
        ar: 'قانون الاتصالات وتكنولوجيا المعلومات',
    },
    {
        fr: 'Droit et management du sport',
        en: 'Sports Law and Management',
        ar: 'قانون الرياضة وإدارتها',
    },
    {
        fr: 'Droit international privé',
        en: 'Private International Law',
        ar: 'القانون الدولي الخاص',
    },
    { fr: "Droit à l'eau", en: 'Right to Water', ar: 'الحق في الماء' },
    { fr: "Droits de l'enfant", en: "Children's Rights", ar: 'حقوق الطفل' },
    { fr: "Droits de l'homme", en: 'Human Rights', ar: 'حقوق الإنسان' },
    { fr: 'Droits des femmes', en: "Women's Rights", ar: 'حقوق المرأة' },
    {
        fr: 'Droits des étrangers',
        en: 'Rights of Foreigners',
        ar: 'حقوق الأجانب',
    },
    {
        fr: 'Droits humains et Droits de la femme',
        en: "Human Rights and Women's Rights",
        ar: 'حقوق الإنسان وحقوق المرأة',
    },
    { fr: 'Développement', en: 'Development', ar: 'التنمية' },
    {
        fr: 'Développement Durable',
        en: 'Sustainable Development',
        ar: 'التنمية المستدامة',
    },
    {
        fr: 'Développement Humain',
        en: 'Human Development',
        ar: 'التنمية البشرية',
    },
    {
        fr: 'Développement Personnel',
        en: 'Personal Development',
        ar: 'التنمية الذاتية',
    },
    {
        fr: 'Développement Territorial',
        en: 'Territorial Development',
        ar: 'التنمية الترابية',
    },
    {
        fr: "Développement d'applications web ITIL",
        en: 'Web Application Development (ITIL)',
        ar: 'تطوير تطبيقات الويب وفق ITIL',
    },
    {
        fr: 'Développement des compétences professionnelles',
        en: 'Professional Skills Development',
        ar: 'تطوير المهارات المهنية',
    },
    {
        fr: 'Développement en Afrique Sub-saharienne',
        en: 'Development in Sub-Saharan Africa',
        ar: 'التنمية في إفريقيا جنوب الصحراء',
    },
    {
        fr: 'Développement humain et social',
        en: 'Human and Social Development',
        ar: 'التنمية البشرية والاجتماعية',
    },
    {
        fr: 'Développement personnel',
        en: 'Personal Development',
        ar: 'التنمية الذاتية',
    },
    {
        fr: 'Développement personnel et professionnel',
        en: 'Personal and Professional Development',
        ar: 'التنمية الذاتية والمهنية',
    },
    {
        fr: 'Développement social',
        en: 'Social Development',
        ar: 'التنمية الاجتماعية',
    },
    { fr: 'E-Business', en: 'E-Business', ar: 'الأعمال الإلكترونية' },
    { fr: 'E-commerce', en: 'E-commerce', ar: 'التجارة الإلكترونية' },
    { fr: 'E-réputation', en: 'E-reputation', ar: 'السمعة الرقمية' },
    {
        fr: 'EDUCATION INCLUSIVE ; ENFANCE et PRÉSCOLAIRE',
        en: 'Inclusive Education; Childhood and Preschool',
        ar: 'التعليم الشامل؛ الطفولة والتعليم الأولي',
    },
    {
        fr: "EXPERT D'ASSURÉ ET INDEMNISATION CORPORELLE DES VICTIMES D'ACCIDENTS DE LA ROUTE",
        en: 'Insurance Expert and Bodily Injury Compensation for Road Accident Victims',
        ar: 'خبير تأمين وتعويض الأضرار الجسدية لضحايا حوادث السير',
    },
    { fr: 'Eau', en: 'Water', ar: 'الماء' },
    { fr: 'Eco-communication', en: 'Eco-communication', ar: 'الاتصال البيئي' },
    { fr: 'Ecologie', en: 'Ecology', ar: 'علم البيئة' },
    { fr: 'Economie', en: 'Economics', ar: 'الاقتصاد' },
    { fr: 'Economie Digitale', en: 'Digital Economy', ar: 'الاقتصاد الرقمي' },
    {
        fr: 'Economie de la construction',
        en: 'Construction Economics',
        ar: 'اقتصاد البناء',
    },
    { fr: 'Economie du sport', en: 'Sports Economics', ar: 'اقتصاد الرياضة' },
    {
        fr: 'Economie sociale et solidaire',
        en: 'Social and Solidarity Economy',
        ar: 'الاقتصاد الاجتماعي والتضامني',
    },
    {
        fr: 'Economie-Politique',
        en: 'Political Economy',
        ar: 'الاقتصاد السياسي',
    },
    {
        fr: 'Economie-politique',
        en: 'Political Economy',
        ar: 'الاقتصاد السياسي',
    },
    { fr: 'Ecriture', en: 'Writing', ar: 'الكتابة' },
    { fr: 'Edition', en: 'Publishing', ar: 'النشر' },
    { fr: 'Education', en: 'Education', ar: 'التربية/التعليم' },
    {
        fr: 'Education & Enseignement',
        en: 'Education and Teaching',
        ar: 'التعليم والتدريس',
    },
    {
        fr: 'Education civique et morale',
        en: 'Civic and Moral Education',
        ar: 'التربية المدنية والأخلاقية',
    },
    {
        fr: "Education et droits de l'homme",
        en: 'Education and Human Rights',
        ar: 'التعليم وحقوق الإنسان',
    },
    {
        fr: 'Education financière',
        en: 'Financial Education',
        ar: 'التثقيف المالي',
    },
    { fr: 'Electronique', en: 'Electronics', ar: 'الإلكترونيات' },
    {
        fr: 'Electronique/Electrique/automatisme',
        en: 'Electronics/Electrical/Automation',
        ar: 'الإلكترونيات/الكهرباء/الأتمتة',
    },
    { fr: 'Embryologie', en: 'Embryology', ar: 'علم الأجنة' },
    { fr: 'Emploi', en: 'Employment', ar: 'التوظيف' },
    { fr: 'Energie nucléaire', en: 'Nuclear Energy', ar: 'الطاقة النووية' },
    {
        fr: 'Energie solaire photovoltaïque',
        en: 'Solar Photovoltaic Energy',
        ar: 'الطاقة الشمسية الكهروضوئية',
    },
    {
        fr: 'Energies renouvelables',
        en: 'Renewable Energy',
        ar: 'الطاقات المتجددة',
    },
    {
        fr: 'Energies renouvelables EnR - Grand Éolien et Hydraulique',
        en: 'Renewable Energy - Large Wind and Hydropower',
        ar: 'الطاقات المتجددة - الرياح الكبرى والطاقة المائية',
    },
    { fr: 'Enseignement', en: 'Teaching', ar: 'التعليم' },
    {
        fr: 'Enseignement supérieur',
        en: 'Higher Education',
        ar: 'التعليم العالي',
    },
    {
        fr: 'Entrepreneuriat Social et Agricole',
        en: 'Social and Agricultural Entrepreneurship',
        ar: 'ريادة الأعمال الاجتماعية والزراعية',
    },
    { fr: 'Entrepreneuriat', en: 'Entrepreneurship', ar: 'ريادة الأعمال' },
    {
        fr: 'Entrepreneuriat social',
        en: 'Social Entrepreneurship',
        ar: 'ريادة الأعمال الاجتماعية',
    },
    { fr: 'Environnement ', en: 'Environment', ar: 'البيئة' },
    {
        fr: 'Environnement & développement durable',
        en: 'Environment and Sustainable Development',
        ar: 'البيئة والتنمية المستدامة',
    },
    { fr: 'Epidémiologie', en: 'Epidemiology', ar: 'علم الوبائيات' },
    { fr: 'Ergonomie', en: 'Ergonomics', ar: 'الهندسة البشرية' },
    { fr: 'Esthétique', en: 'Aesthetics/Beauty', ar: 'التجميل' },
    { fr: 'Ethique', en: 'Ethics', ar: 'الأخلاقيات' },
    {
        fr: 'Ethique et Justice Climatique',
        en: 'Ethics and Climate Justice',
        ar: 'الأخلاقيات والعدالة المناخية',
    },
    { fr: 'Etudes de marche', en: 'Market Studies', ar: 'دراسات السوق' },
    { fr: 'Evènementiel', en: 'Event Management', ar: 'تنظيم الفعاليات' },
    { fr: 'Expert Comptable', en: 'Chartered Accountant', ar: 'خبير محاسبي' },
    {
        fr: 'Expert marché afrique',
        en: 'Africa Market Expert',
        ar: 'خبير سوق إفريقيا',
    },
    {
        fr: 'Expertise Immobilière - Médiation',
        en: 'Real Estate Expertise - Mediation',
        ar: 'خبرة عقارية - وساطة',
    },
    {
        fr: 'Expertise en hygiène et sécurité sanitaire',
        en: 'Hygiene and Health Safety Expertise',
        ar: 'خبرة في النظافة والسلامة الصحية',
    },
    { fr: 'Export', en: 'Export', ar: 'التصدير' },
    {
        fr: 'Export of British education',
        en: 'Export of British Education',
        ar: 'تصدير التعليم البريطاني',
    },
    { fr: 'Expérience client', en: 'Customer Experience', ar: 'تجربة الزبون' },
    { fr: 'Fantasia Tbourida', en: 'Fantasia Tbourida', ar: 'التبوريدة' },
    { fr: 'Feng Shui', en: 'Feng Shui', ar: 'فنغ شوي' },
    {
        fr: 'Fertilisation silicatée et Biodiversité',
        en: 'Silicate Fertilization and Biodiversity',
        ar: 'التسميد السيليكاتي والتنوع البيولوجي',
    },
    { fr: 'Fidelisation client', en: 'Customer Loyalty', ar: 'ولاء العملاء' },
    { fr: 'Finance Islamique', en: 'Islamic Finance', ar: 'التمويل الإسلامي' },
    {
        fr: 'Finance participative',
        en: 'Participatory Finance',
        ar: 'التمويل التشاركي',
    },
    { fr: 'Financement', en: 'Financing', ar: 'التمويل' },
    { fr: 'Finances', en: 'Finance', ar: 'المالية' },
    { fr: 'Finances Publiques', en: 'Public Finance', ar: 'المالية العامة' },
    { fr: 'Fiscalité', en: 'Taxation', ar: 'الضرائب' },
    { fr: 'Formation', en: 'Training', ar: 'التكوين' },
    {
        fr: 'Formatrice en RP et en prise de parole en public',
        en: 'PR and Public Speaking Trainer',
        ar: 'مدربة في العلاقات العامة والتحدث أمام الجمهور',
    },
    { fr: 'Féminisme', en: 'Feminism', ar: 'النسوية' },
    { fr: 'Genre', en: 'Gender', ar: 'النوع الاجتماعي' },
    {
        fr: 'Genre et Rapports sociaux de sexe',
        en: 'Gender and Social Relations',
        ar: 'النوع الاجتماعي والعلاقات الاجتماعية',
    },
    {
        fr: 'Genre, Médias, questions sociologiques et de citoyenneté',
        en: 'Gender, Media, Sociological and Citizenship Issues',
        ar: 'النوع الاجتماعي والإعلام والقضايا السوسيولوجية والمواطنة',
    },
    {
        fr: 'Gestion de Projets',
        en: 'Project Management',
        ar: 'إدارة المشاريع',
    },
    {
        fr: 'Gestion de la chaîne logistique',
        en: 'Supply Chain Management',
        ar: 'إدارة سلسلة الإمداد',
    },
    {
        fr: 'Gestion de patrimoine',
        en: 'Wealth Management',
        ar: 'إدارة الثروة',
    },
    {
        fr: 'Gestion de portefeuilles',
        en: 'Portfolio Management',
        ar: 'إدارة المحافظ',
    },
    {
        fr: 'Gestion de projet/Scrum Master',
        en: 'Project Management/Scrum Master',
        ar: 'إدارة المشاريع/سكروم ماستر',
    },
    {
        fr: 'Gestion des données cliniques',
        en: 'Clinical Data Management',
        ar: 'إدارة البيانات السريرية',
    },
    {
        fr: 'Gestion des déchets solides',
        en: 'Solid Waste Management',
        ar: 'إدارة النفايات الصلبة',
    },
    {
        fr: 'Gestion des entreprises',
        en: 'Business Management',
        ar: 'إدارة الأعمال',
    },
    {
        fr: 'Gestion des ressources humaines',
        en: 'Human Resources Management',
        ar: 'إدارة الموارد البشرية',
    },
    {
        fr: 'Gestion électronique des documents',
        en: 'Electronic Document Management',
        ar: 'إدارة الوثائق الإلكترونية',
    },
    { fr: 'Gouvernance', en: 'Governance', ar: 'الحكامة' },
    {
        fr: 'Gouvernance - Genre - Jeunesse',
        en: 'Governance - Gender - Youth',
        ar: 'الحكامة - النوع الاجتماعي - الشباب',
    },
    {
        fr: 'Gouvernance et ingénierie de la participation publique',
        en: 'Governance and Public Participation Engineering',
        ar: 'الحكامة وهندسة المشاركة العمومية',
    },
    { fr: 'Grand Eolien', en: 'Large Wind Power', ar: 'طاقة الرياح الكبيرة' },
    {
        fr: 'Gynécologie-obstétrique',
        en: 'Gynecology-Obstetrics',
        ar: 'طب النساء والتوليد',
    },
    { fr: 'Génie Logiciel', en: 'Software Engineering', ar: 'هندسة البرمجيات' },
    { fr: 'Génie civil', en: 'Civil Engineering', ar: 'الهندسة المدنية' },
    {
        fr: 'Génie industriel',
        en: 'Industrial Engineering',
        ar: 'الهندسة الصناعية',
    },
    {
        fr: 'Génie mécanique',
        en: 'Mechanical Engineering',
        ar: 'الهندسة الميكانيكية',
    },
    {
        fr: 'Génie électrique et automatique',
        en: 'Electrical and Automation Engineering',
        ar: 'الهندسة الكهربائية والأتمتة',
    },
    { fr: 'Géochimie', en: 'Geochemistry', ar: 'الجيوكيمياء' },
    { fr: 'Géologie', en: 'Geology', ar: 'الجيولوجيا' },
    { fr: 'Géopolitique', en: 'Geopolitics', ar: 'الجيوسياسة' },
    {
        fr: 'Géopolitique de la santé',
        en: 'Health Geopolitics',
        ar: 'جيوسياسة الصحة',
    },
    {
        fr: 'Géopolitique sanitaire',
        en: 'Health Geopolitics',
        ar: 'الجيوسياسة الصحية',
    },
    { fr: 'Handicap', en: 'Disability', ar: 'الإعاقة' },
    { fr: 'Histoire', en: 'History', ar: 'التاريخ' },
    { fr: 'Horticulture', en: 'Horticulture', ar: 'البستنة' },
    { fr: 'Hydraulique', en: 'Hydraulics', ar: 'الهيدروليك' },
    {
        fr: 'Hypnothérapie',
        en: 'Hypnotherapy',
        ar: 'العلاج بالتنويم المغناطيسي',
    },
    { fr: 'Héritage', en: 'Heritage', ar: 'التراث' },
    {
        fr: 'Hôtellerie et restauration',
        en: 'Hospitality and Catering',
        ar: 'الفندقة والمطاعم',
    },
    { fr: 'Immobilier', en: 'Real Estate', ar: 'العقار' },
    {
        fr: 'Imprimerie et arts graphiques',
        en: 'Printing and Graphic Arts',
        ar: 'الطباعة والفنون الغرافيكية',
    },
    {
        fr: 'Inclusion socio-économique des jeunes',
        en: 'Socio-economic Inclusion of Youth',
        ar: 'الإدماج الاجتماعي والاقتصادي للشباب',
    },
    { fr: 'Industrie', en: 'Industry', ar: 'الصناعة' },
    {
        fr: 'Industrie automobile',
        en: 'Automotive Industry',
        ar: 'صناعة السيارات',
    },
    { fr: 'Industrie du bois', en: 'Wood Industry', ar: 'صناعة الخشب' },
    {
        fr: 'Industries Agroalimentaires',
        en: 'Agro-food Industries',
        ar: 'الصناعات الغذائية الزراعية',
    },
    { fr: 'Informatique', en: 'Computer Science/IT', ar: 'المعلوماتية' },
    {
        fr: 'Informatique décisionnelle',
        en: 'Business Intelligence',
        ar: 'المعلوماتية القرارَية',
    },
    {
        fr: 'Ingénierie Réseaux et Télécom',
        en: 'Network and Telecom Engineering',
        ar: 'هندسة الشبكات والاتصالات',
    },
    {
        fr: 'Ingénierie de développement humain et territorial durable',
        en: 'Sustainable Human and Territorial Development Engineering',
        ar: 'هندسة التنمية البشرية والترابية المستدامة',
    },
    {
        fr: 'Ingénierie des Matériaux Composites',
        en: 'Composite Materials Engineering',
        ar: 'هندسة المواد المركبة',
    },
    {
        fr: 'Ingénierie mécanique',
        en: 'Mechanical Engineering',
        ar: 'الهندسة الميكانيكية',
    },
    {
        fr: 'Ingénierie sociale',
        en: 'Social Engineering',
        ar: 'الهندسة الاجتماعية',
    },
    {
        fr: 'Ingénierie statistique',
        en: 'Statistical Engineering',
        ar: 'الهندسة الإحصائية',
    },
    {
        fr: 'Ingénierie topographique',
        en: 'Topographic Engineering',
        ar: 'الهندسة الطبوغرافية',
    },
    { fr: 'Innovation', en: 'Innovation', ar: 'الابتكار' },
    {
        fr: 'Innovation digitale',
        en: 'Digital Innovation',
        ar: 'الابتكار الرقمي',
    },
    {
        fr: 'Innovation sociale',
        en: 'Social Innovation',
        ar: 'الابتكار الاجتماعي',
    },
    { fr: 'Inondations', en: 'Floods', ar: 'الفيضانات' },
    {
        fr: 'Intelligence Artificielle',
        en: 'Artificial Intelligence',
        ar: 'الذكاء الاصطناعي',
    },
    {
        fr: 'Intelligence économique',
        en: 'Economic Intelligence',
        ar: 'اليقظة الاقتصادية',
    },
    {
        fr: 'International freight forwarder ',
        en: 'International Freight Forwarder',
        ar: 'وسيط الشحن الدولي',
    },
    { fr: 'Jeunesse', en: 'Youth', ar: 'الشباب' },
    { fr: 'Journalisme', en: 'Journalism', ar: 'الصحافة' },
    { fr: 'Justice', en: 'Justice', ar: 'العدالة' },
    { fr: 'Kinésitherapie', en: 'Physiotherapy', ar: 'العلاج الطبيعي' },
    {
        fr: "L'activation et la présentation, la radio",
        en: 'Radio Hosting and Presentation',
        ar: 'التنشيط والتقديم الإذاعي',
    },
    {
        fr: 'La recherche scientifique',
        en: 'Scientific Research',
        ar: 'البحث العلمي',
    },
    { fr: 'Leadership', en: 'Leadership', ar: 'القيادة' },
    {
        fr: 'Learning Management System',
        en: 'Learning Management System',
        ar: 'نظام إدارة التعلم',
    },
    {
        fr: "Les Systèmes d'Informations (ERP)",
        en: 'Information Systems (ERP)',
        ar: 'نظم المعلومات (ERP)',
    },
    {
        fr: 'Libertés individuelles',
        en: 'Individual Liberties',
        ar: 'الحريات الفردية',
    },
    { fr: 'Littérature ', en: 'Literature', ar: 'الأدب' },
    { fr: 'Logic and Language', en: 'Logic and Language', ar: 'المنطق واللغة' },
    {
        fr: 'Logistique internationale',
        en: 'International Logistics',
        ar: 'اللوجستيك الدولي',
    },
    { fr: 'Lovecoaching', en: 'Love Coaching', ar: 'تدريب العلاقات العاطفية' },
    {
        fr: "Lutte contre l'exclusion sociale et prise en charge médico- psycho- sociale de ces populations",
        en: 'Fight against Social Exclusion and Medical-Psycho-Social Support',
        ar: 'مكافحة الإقصاء الاجتماعي والرعاية الطبية-النفسية-الاجتماعية',
    },
    {
        fr: 'Lutte contre la drogue',
        en: 'Fight against Drugs',
        ar: 'مكافحة المخدرات',
    },
    {
        fr: 'Lutte et prévention contre l’extrémisme violent',
        en: 'Fight and Prevention of Violent Extremism',
        ar: 'مكافحة والوقاية من التطرف العنيف',
    },
    {
        fr: 'Maintenance et Asset management',
        en: 'Maintenance and Asset Management',
        ar: 'الصيانة وإدارة الأصول',
    },
    {
        fr: 'Maintenance mécanique électronique',
        en: 'Mechanical and Electronic Maintenance',
        ar: 'الصيانة الميكانيكية والإلكترونية',
    },
    { fr: 'Management', en: 'Management', ar: 'الإدارة' },
    {
        fr: 'Management Sûreté et Sécurité',
        en: 'Safety and Security Management',
        ar: 'إدارة السلامة والأمن',
    },
    {
        fr: "Management de crise et de la continuité d'activité",
        en: 'Crisis Management and Business Continuity',
        ar: 'إدارة الأزمات واستمرارية الأعمال',
    },
    {
        fr: 'Management des Ressources Humaines',
        en: 'Human Resources Management',
        ar: 'إدارة الموارد البشرية',
    },
    {
        fr: 'Management des systèmes d’information',
        en: 'Information Systems Management',
        ar: 'إدارة نظم المعلومات',
    },
    {
        fr: 'Marché Publicitaire',
        en: 'Advertising Market',
        ar: 'سوق الإعلانات',
    },
    { fr: 'Marchés Publics', en: 'Public Procurement', ar: 'الصفقات العمومية' },
    { fr: 'Mariage ', en: 'Marriage', ar: 'الزواج' },
    { fr: 'Mariage des mineures', en: 'Child Marriage', ar: 'زواج القاصرات' },
    { fr: 'Maritime', en: 'Maritime', ar: 'البحري' },
    { fr: 'Marketing', en: 'Marketing', ar: 'التسويق' },
    {
        fr: 'Marketing & Communication',
        en: 'Marketing and Communication',
        ar: 'التسويق والاتصال',
    },
    { fr: 'Marketing Digital', en: 'Digital Marketing', ar: 'التسويق الرقمي' },
    {
        fr: 'Marketing et développement territorial',
        en: 'Marketing and Territorial Development',
        ar: 'التسويق والتنمية الترابية',
    },
    {
        fr: 'Mathématiques appliquées',
        en: 'Applied Mathematics',
        ar: 'الرياضيات التطبيقية',
    },
    {
        fr: 'Matériaux composites',
        en: 'Composite Materials',
        ar: 'المواد المركبة',
    },
    { fr: 'Maîtresse', en: 'Teacher', ar: 'معلمة' },
    {
        fr: "Mesures pour l'emploi",
        en: 'Employment Measures',
        ar: 'إجراءات من أجل التشغيل',
    },
    { fr: 'Microfinance', en: 'Microfinance', ar: 'التمويل الأصغر' },
    {
        fr: 'Mise en relation B to B',
        en: 'B2B Matchmaking',
        ar: 'الربط بين الشركات (B2B)',
    },
    { fr: 'Mode ', en: 'Fashion', ar: 'الأزياء' },
    { fr: 'Mode enfants', en: "Children's Fashion", ar: 'أزياء الأطفال' },
    { fr: 'Musicologie', en: 'Musicology', ar: 'علم الموسيقى' },
    {
        fr: 'Mécanique & fiabilité des systèmes',
        en: 'Mechanics and Systems Reliability',
        ar: 'الميكانيك وموثوقية الأنظمة',
    },
    {
        fr: 'Mécanismes de développement culturel',
        en: 'Cultural Development Mechanisms',
        ar: 'آليات التنمية الثقافية',
    },
    { fr: 'Médecine', en: 'Medicine', ar: 'الطب' },
    { fr: 'Médecine du sport', en: 'Sports Medicine', ar: 'طب الرياضة' },
    { fr: 'Médias ', en: 'Media', ar: 'الإعلام' },
    {
        fr: "Médias, droits de l'homme et société civile",
        en: 'Media, Human Rights and Civil Society',
        ar: 'الإعلام وحقوق الإنسان والمجتمع المدني',
    },
    {
        fr: 'Médiation familiale',
        en: 'Family Mediation',
        ar: 'الوساطة الأسرية',
    },
    { fr: 'Météorites', en: 'Meteorites', ar: 'النيازك' },
    {
        fr: 'Météorites Planétologie',
        en: 'Meteorites and Planetology',
        ar: 'النيازك وعلم الكواكب',
    },
    { fr: 'Nanotechnologies', en: 'Nanotechnology', ar: 'التقنيات النانوية' },
    { fr: 'Notariat', en: 'Notary', ar: 'التوثيق' },
    { fr: 'Numérique', en: 'Digital', ar: 'الرقمي' },
    {
        fr: 'Nutrition et Diététique',
        en: 'Nutrition and Dietetics',
        ar: 'التغذية والحمية',
    },
    {
        fr: 'Néphrologie pédiatrique',
        en: 'Pediatric Nephrology',
        ar: 'أمراض الكلى لدى الأطفال',
    },
    { fr: 'Oceanographe', en: 'Oceanographer', ar: 'علم المحيطات' },
    {
        fr: 'Oncogénétique, conseil génétique',
        en: 'Oncogenetics, Genetic Counseling',
        ar: 'الوراثة السرطانية والاستشارة الوراثية',
    },
    { fr: 'Ophtalmologie', en: 'Ophthalmology', ar: 'طب العيون' },
    { fr: 'Organisation', en: 'Organization', ar: 'التنظيم' },
    {
        fr: "Orientation et Recrutement à l'international",
        en: 'International Guidance and Recruitment',
        ar: 'التوجيه والتوظيف الدولي',
    },
    {
        fr: "Orientation et inscription à l'International",
        en: 'International Guidance and Enrollment',
        ar: 'التوجيه والتسجيل الدولي',
    },
    {
        fr: 'Orientation scolaire',
        en: 'School Guidance',
        ar: 'التوجيه المدرسي',
    },
    {
        fr: 'Orientation scolaire et professionnelle',
        en: 'Educational and Career Guidance',
        ar: 'التوجيه المدرسي والمهني',
    },
    { fr: 'Orthophoniste', en: 'Speech Therapist', ar: 'أخصائي النطق' },
    { fr: 'Patisserie', en: 'Pastry', ar: 'الحلويات' },
    { fr: 'Patrimoine', en: 'Heritage', ar: 'التراث' },
    {
        fr: 'Patrimoine spirituel',
        en: 'Spiritual Heritage',
        ar: 'التراث الروحي',
    },
    { fr: 'Petite enfance', en: 'Early Childhood', ar: 'الطفولة المبكرة' },
    {
        fr: 'Pharmacovigilance ',
        en: 'Pharmacovigilance',
        ar: 'اليقظة الدوائية',
    },
    { fr: 'Photographie', en: 'Photography', ar: 'التصوير' },
    { fr: 'Photothérapie', en: 'Phototherapy', ar: 'العلاج بالضوء' },
    { fr: 'Physiothérapie', en: 'Physiotherapy', ar: 'العلاج الطبيعي' },
    {
        fr: 'Physiothérapie, kinésithérapie',
        en: 'Physiotherapy and Kinesitherapy',
        ar: 'العلاج الطبيعي والعلاج الحركي',
    },
    { fr: 'Physique nucléaire', en: 'Nuclear Physics', ar: 'الفيزياء النووية' },
    { fr: 'Plaidoyer', en: 'Advocacy', ar: 'المناصرة' },
    { fr: 'Planétologie', en: 'Planetology', ar: 'علم الكواكب' },
    { fr: 'Pneumologie', en: 'Pulmonology', ar: 'طب الرئة' },
    { fr: 'Podologue', en: 'Podiatrist', ar: 'أخصائي القدم' },
    { fr: 'Politique', en: 'Politics', ar: 'السياسة' },
    { fr: 'Politique Monétaire', en: 'Monetary Policy', ar: 'السياسة النقدية' },
    {
        fr: 'Politique international',
        en: 'International Politics',
        ar: 'السياسة الدولية',
    },
    { fr: 'Politique étrangère', en: 'Foreign Policy', ar: 'السياسة الخارجية' },
    { fr: 'Poésie', en: 'Poetry', ar: 'الشعر' },
    {
        fr: 'Prevention et Excellence par le coaching neuronal',
        en: 'Prevention and Excellence through Neuro Coaching',
        ar: 'الوقاية والتميز عبر التدريب العصبي',
    },
    {
        fr: 'Production audiovisuelle',
        en: 'Audiovisual Production',
        ar: 'الإنتاج السمعي البصري',
    },
    {
        fr: 'Production cinematographique, Television, Documentaires',
        en: 'Film, TV and Documentary Production',
        ar: 'الإنتاج السينمائي والتلفزيوني والوثائقي',
    },
    {
        fr: 'Production de projets',
        en: 'Project Production',
        ar: 'إنتاج المشاريع',
    },
    {
        fr: 'Professionnalisation du football',
        en: 'Football Professionalization',
        ar: 'احتراف كرة القدم',
    },
    {
        fr: 'Programmation Neuro linguistique',
        en: 'Neuro-Linguistic Programming',
        ar: 'البرمجة اللغوية العصبية',
    },
    {
        fr: "Promotion de la femme dans les technologies de l'Information",
        en: 'Women Promotion in IT',
        ar: 'تمكين المرأة في تكنولوجيا المعلومات',
    },
    {
        fr: "Promotion et Admission à l'international",
        en: 'International Promotion and Admission',
        ar: 'الترويج والقبول الدولي',
    },
    {
        fr: 'Protection des consommateurs',
        en: 'Consumer Protection',
        ar: 'حماية المستهلك',
    },
    {
        fr: 'Protection sociale',
        en: 'Social Protection',
        ar: 'الحماية الاجتماعية',
    },
    {
        fr: "Prévention de la violence sexuelle à l'encontre des enfants",
        en: 'Prevention of Sexual Violence against Children',
        ar: 'الوقاية من العنف الجنسي ضد الأطفال',
    },
    {
        fr: 'Prévention routière',
        en: 'Road Safety Prevention',
        ar: 'الوقاية الطرقية',
    },
    { fr: 'Psychiatrie', en: 'Psychiatry', ar: 'الطب النفسي' },
    { fr: 'Psychologie', en: 'Psychology', ar: 'علم النفس' },
    {
        fr: 'Psychologie du travail',
        en: 'Occupational Psychology',
        ar: 'علم النفس المهني',
    },
    {
        fr: 'Psychologie énergétique et comportementale',
        en: 'Energetic and Behavioral Psychology',
        ar: 'علم النفس الطاقي والسلوكي',
    },
    {
        fr: 'Psychomotricité',
        en: 'Psychomotricity',
        ar: 'العلاج النفسي الحركي',
    },
    { fr: 'Psychotérapie', en: 'Psychotherapy', ar: 'العلاج النفسي' },
    { fr: 'Public Finance', en: 'Public Finance', ar: 'المالية العامة' },
    {
        fr: 'Pédagogie/ Andragogie',
        en: 'Pedagogy/Andragogy',
        ar: 'البيداغوجيا وتعليم الكبار',
    },
    { fr: 'Pédopsychiatrie', en: 'Child Psychiatry', ar: 'طب نفس الأطفال' },
    {
        fr: 'Qualite santé Securite ét environnement au travail',
        en: 'Health, Safety and Environment at Work',
        ar: 'الصحة والسلامة والبيئة في العمل',
    },
    {
        fr: 'Qualité - Process',
        en: 'Quality - Process',
        ar: 'الجودة - العمليات',
    },
    {
        fr: 'Radionavigation aérienne',
        en: 'Air Radionavigation',
        ar: 'الملاحة الجوية الراديوية',
    },
    {
        fr: 'Recherche Pharmaceutique',
        en: 'Pharmaceutical Research',
        ar: 'البحث الصيدلاني',
    },
    {
        fr: 'Recherche dans les Sciences humaines',
        en: 'Research in Human Sciences',
        ar: 'البحث في العلوم الإنسانية',
    },
    {
        fr: 'Recherche et développement ',
        en: 'Research and Development',
        ar: 'البحث والتطوير',
    },
    { fr: 'Recrutement', en: 'Recruitment', ar: 'التوظيف' },
    { fr: 'Recyclage', en: 'Recycling', ar: 'إعادة التدوير' },
    { fr: 'Relation presse', en: 'Press Relations', ar: 'العلاقات الصحفية' },
    {
        fr: 'Relations Internationales',
        en: 'International Relations',
        ar: 'العلاقات الدولية',
    },
    {
        fr: 'Relations economiques marocco-américaines et Accord du libre échange',
        en: 'Moroccan-American Economic Relations and Free Trade Agreement',
        ar: 'العلاقات الاقتصادية المغربية-الأمريكية واتفاقية التبادل الحر',
    },
    {
        fr: 'Relations presse / relations publiques',
        en: 'Press Relations / Public Relations',
        ar: 'العلاقات الصحفية/العلاقات العامة',
    },
    {
        fr: 'Relations publiques',
        en: 'Public Relations',
        ar: 'العلاقات العامة',
    },
    {
        fr: 'Représentation des femmes dans les médias',
        en: 'Representation of Women in Media',
        ar: 'تمثيل النساء في الإعلام',
    },
    {
        fr: 'Responsabilité Sociétale des Entreprises',
        en: 'Corporate Social Responsibility',
        ar: 'المسؤولية الاجتماعية للشركات',
    },
    { fr: 'Ressources Humaines', en: 'Human Resources', ar: 'الموارد البشرية' },
    { fr: 'Restauration', en: 'Catering/Restaurant', ar: 'المطعمة والمطاعم' },
    {
        fr: 'Risques Opérationnels',
        en: 'Operational Risks',
        ar: 'المخاطر التشغيلية',
    },
    {
        fr: 'Réanimation médicale',
        en: 'Intensive Care Medicine',
        ar: 'الإنعاش الطبي',
    },
    { fr: 'Réassurance', en: 'Reinsurance', ar: 'إعادة التأمين' },
    {
        fr: 'Réchauffement climatique ',
        en: 'Global Warming',
        ar: 'الاحترار المناخي',
    },
    { fr: 'Référencement', en: 'SEO', ar: 'تحسين محركات البحث' },
    {
        fr: 'Régie publicitaire',
        en: 'Advertising Sales/Management',
        ar: 'تسيير الإشهار',
    },
    {
        fr: "Réseaux et Systèmes d'information",
        en: 'Networks and Information Systems',
        ar: 'الشبكات ونظم المعلومات',
    },
    {
        fr: 'Résolution des conflits',
        en: 'Conflict Resolution',
        ar: 'حل النزاعات',
    },
    { fr: 'SEO', en: 'SEO', ar: 'تحسين محركات البحث' },
    { fr: 'Sales& Retail', en: 'Sales and Retail', ar: 'المبيعات والتجزئة' },
    { fr: 'Santé ', en: 'Health', ar: 'الصحة' },
    {
        fr: 'Santé - Ergonomie au travail',
        en: 'Health - Ergonomics at Work',
        ar: 'الصحة والهندسة البشرية في العمل',
    },
    { fr: 'Santé enfants', en: 'Child Health', ar: 'صحة الأطفال' },
    {
        fr: 'Santé-Ergonomie au travail',
        en: 'Health and Ergonomics at Work',
        ar: 'الصحة والهندسة البشرية في العمل',
    },
    {
        fr: 'Science de l’éducation',
        en: 'Education Science',
        ar: 'علوم التربية',
    },
    { fr: 'Sciences', en: 'Sciences', ar: 'العلوم' },
    {
        fr: 'Sciences de gestion',
        en: 'Management Sciences',
        ar: 'علوم التسيير',
    },
    { fr: 'Sciences du langage', en: 'Language Sciences', ar: 'علوم اللغة' },
    {
        fr: 'Sciences et technologie du Bois',
        en: 'Wood Science and Technology',
        ar: 'علوم وتكنولوجيا الخشب',
    },
    {
        fr: 'Sciences humaines et sociales ',
        en: 'Human and Social Sciences',
        ar: 'العلوم الإنسانية والاجتماعية',
    },
    { fr: 'Sciences infirmièrs', en: 'Nursing Sciences', ar: 'علوم التمريض' },
    {
        fr: 'Sciences politiques et Relations internationales Contemporaines',
        en: 'Political Science and Contemporary International Relations',
        ar: 'العلوم السياسية والعلاقات الدولية المعاصرة',
    },
    {
        fr: 'Sciences urologiques',
        en: 'Urological Sciences',
        ar: 'علوم المسالك البولية',
    },
    {
        fr: 'Scolarisation des filles rurales',
        en: 'Schooling of Rural Girls',
        ar: 'تمدرس الفتيات القرويات',
    },
    { fr: 'Scénariste', en: 'Screenwriter', ar: 'كاتب سيناريو' },
    {
        fr: 'Sensibilisation médicale',
        en: 'Medical Awareness',
        ar: 'التوعية الطبية',
    },
    {
        fr: 'Sexologie et Thérapie de Couples',
        en: 'Sexology and Couples Therapy',
        ar: 'علم الجنس وعلاج الأزواج',
    },
    { fr: 'Social Media', en: 'Social Media', ar: 'وسائل التواصل الاجتماعي' },
    {
        fr: 'Social chez enfants et. Et ado',
        en: 'Social for Children and Teens',
        ar: 'الجانب الاجتماعي لدى الأطفال والمراهقين',
    },
    { fr: 'Sociologue', en: 'Sociologist', ar: 'عالم اجتماع' },
    { fr: 'Société civile ', en: 'Civil Society', ar: 'المجتمع المدني' },
    { fr: 'Soins Infirmiers', en: 'Nursing Care', ar: 'رعاية تمريضية' },
    { fr: 'Sophrologie', en: 'Sophrology', ar: 'السوفروولوجيا' },
    { fr: 'Soufisme', en: 'Sufism', ar: 'التصوف' },
    {
        fr: 'Soutien de la femme battue',
        en: 'Support for Abused Women',
        ar: 'دعم النساء المعنفات',
    },
    { fr: 'Sport', en: 'Sport', ar: 'الرياضة' },
    {
        fr: "Spécialiste de l'Afrique",
        en: 'Africa Specialist',
        ar: 'متخصص في إفريقيا',
    },
    {
        fr: 'Stabilisation et développement dans les zones de conflits',
        en: 'Stabilization and Development in Conflict Zones',
        ar: 'الاستقرار والتنمية في مناطق النزاع',
    },
    {
        fr: 'Stratégie Marketing et Communication',
        en: 'Marketing and Communication Strategy',
        ar: 'استراتيجية التسويق والاتصال',
    },
    {
        fr: 'Stratégie communication',
        en: 'Communication Strategy',
        ar: 'استراتيجية الاتصال',
    },
    {
        fr: "Stratégie d'entreprise",
        en: 'Business Strategy',
        ar: 'استراتيجية المؤسسة',
    },
    { fr: 'Stylisme', en: 'Fashion Design', ar: 'تصميم الأزياء' },
    {
        fr: "Suivi des contrats d'investissement",
        en: 'Monitoring Investment Contracts',
        ar: 'تتبع عقود الاستثمار',
    },
    { fr: 'Synergologie', en: 'Synergology', ar: 'السِّينرغولوجيا' },
    {
        fr: 'Synérgologie et Marketing politique',
        en: 'Synergology and Political Marketing',
        ar: 'السِّينرغولوجيا والتسويق السياسي',
    },
    { fr: 'Sécurité Incendie', en: 'Fire Safety', ar: 'السلامة من الحرائق' },
    { fr: 'Sécurité Routière', en: 'Road Safety', ar: 'السلامة الطرقية' },
    { fr: 'Sécurité Santé', en: 'Health Safety', ar: 'السلامة الصحية' },
    {
        fr: 'Sécurité alimentaire, biotechnologie agroalimentaire',
        en: 'Food Safety, Agro-food Biotechnology',
        ar: 'سلامة الغذاء والتكنولوجيا الحيوية الغذائية',
    },
    {
        fr: 'Sécurité des denrées alimentaires',
        en: 'Food Safety of Products',
        ar: 'سلامة المواد الغذائية',
    },
    {
        fr: 'Sécurité des moyens de paiement',
        en: 'Payment Security',
        ar: 'أمن وسائل الدفع',
    },
    {
        fr: 'Sécurité et Défense Internationale',
        en: 'International Security and Defense',
        ar: 'الأمن والدفاع الدولي',
    },
    { fr: 'Sécurité incendie', en: 'Fire Safety', ar: 'السلامة من الحرائق' },
    {
        fr: 'Sécurité informatique',
        en: 'Information Security',
        ar: 'أمن المعلومات',
    },
    { fr: 'Sécurité sociale', en: 'Social Security', ar: 'الضمان الاجتماعي' },
    {
        fr: 'Sûreté et sécurité nucléaires',
        en: 'Nuclear Safety and Security',
        ar: 'السلامة والأمن النوويان',
    },
    {
        fr: "Techniques d'imprimerie",
        en: 'Printing Techniques',
        ar: 'تقنيات الطباعة',
    },
    { fr: 'Textile', en: 'Textile', ar: 'النسيج' },
    { fr: 'Théâtre', en: 'Theater', ar: 'المسرح' },
    { fr: 'Tourisme', en: 'Tourism', ar: 'السياحة' },
    { fr: "Tourisme d'affaires", en: 'Business Tourism', ar: 'سياحة الأعمال' },
    {
        fr: 'Tourisme et hôtellerie',
        en: 'Tourism and Hospitality',
        ar: 'السياحة والفندقة',
    },
    {
        fr: 'Traduction audiovisuelle - sous-titrage - audiodescription',
        en: 'Audiovisual Translation - Subtitling - Audio Description',
        ar: 'الترجمة السمعية البصرية - الترجمة النصية - الوصف السمعي',
    },
    {
        fr: 'Traduction et Interprétation',
        en: 'Translation and Interpretation',
        ar: 'الترجمة والتحرير الفوري',
    },
    { fr: 'Traitement des eaux', en: 'Water Treatment', ar: 'معالجة المياه' },
    {
        fr: 'Transformation digitale',
        en: 'Digital Transformation',
        ar: 'التحول الرقمي',
    },
    { fr: 'Transport', en: 'Transport', ar: 'النقل' },
    { fr: 'Transport aérien', en: 'Air Transport', ar: 'النقل الجوي' },
    { fr: 'Transport maritime', en: 'Maritime Transport', ar: 'النقل البحري' },
    { fr: 'Travail Associatif', en: 'Associative Work', ar: 'العمل الجمعوي' },
    { fr: 'Travail des enfants', en: 'Child Labor', ar: 'عمل الأطفال' },
    { fr: 'Télécommunications', en: 'Telecommunications', ar: 'الاتصالات' },
    { fr: 'Urbanisme', en: 'Urban Planning', ar: 'التهيئة العمرانية' },
    {
        fr: 'Veille et intelligence économique',
        en: 'Economic Intelligence and Monitoring',
        ar: 'اليقظة والذكاء الاقتصادي',
    },
    {
        fr: 'Violence à l’égard des femmes',
        en: 'Violence against Women',
        ar: 'العنف ضد النساء',
    },
    {
        fr: 'Vision par Ordinateur',
        en: 'Computer Vision',
        ar: 'الرؤية الحاسوبية',
    },
    {
        fr: 'Vulgarisation Scientifique',
        en: 'Scientific Popularization',
        ar: 'تبسيط العلوم',
    },
    {
        fr: 'Web marketing et design',
        en: 'Web Marketing and Design',
        ar: 'التسويق والتصميم الرقمي',
    },
    { fr: 'audit interne', en: 'Internal Audit', ar: 'التدقيق الداخلي' },
    {
        fr: "chirurgienne orthopédiste traumatologue et professeur de l'enseignement supérieure",
        en: 'Orthopedic Trauma Surgeon and Higher Education Professor',
        ar: 'جراحة عظام وإصابات وأستاذة تعليم عالٍ',
    },
    {
        fr: 'cuisine gastronomique',
        en: 'Gastronomic Cuisine',
        ar: 'المطبخ الراقي',
    },
    {
        fr: 'direction artistique',
        en: 'Artistic Direction',
        ar: 'الإخراج الفني',
    },
    {
        fr: 'développement des compétences par la formation',
        en: 'Skills Development through Training',
        ar: 'تنمية المهارات عبر التكوين',
    },
    {
        fr: 'enseignement supérieur',
        en: 'Higher Education',
        ar: 'التعليم العالي',
    },
    { fr: 'industrie pétrolière', en: 'Oil Industry', ar: 'صناعة النفط' },
    {
        fr: 'maladies autoimmunes et rares',
        en: 'Autoimmune and Rare Diseases',
        ar: 'أمراض المناعة الذاتية والنادرة',
    },
    {
        fr: 'management librarie',
        en: 'Bookstore Management',
        ar: 'إدارة مكتبة',
    },
    {
        fr: 'montage, management et évaluation de projets',
        en: 'Project Planning, Management and Evaluation',
        ar: 'إعداد وتسيير وتقييم المشاريع',
    },
    { fr: 'médecine dentaire', en: 'Dentistry', ar: 'طب الأسنان' },
    {
        fr: 'responsabilité sociale et environnementale',
        en: 'Social and Environmental Responsibility',
        ar: 'المسؤولية الاجتماعية والبيئية',
    },
    { fr: 'traduction', en: 'Translation', ar: 'ترجمة' },
    {
        fr: 'Éducation financière',
        en: 'Financial Education',
        ar: 'التثقيف المالي',
    },
    { fr: 'Élections', en: 'Elections', ar: 'الانتخابات' },
    { fr: 'Électricité', en: 'Electricity', ar: 'الكهرباء' },
    {
        fr: 'Établissements scolaires',
        en: 'Educational Institutions',
        ar: 'المؤسسات التعليمية',
    },
];
