export const EVENTS = [
    {
        id: 'tilitalk-women-leading-tech-innovation',
        type: 'talk',
        badge: 'Next event',
        dateIso: '2026-04-12',
        dateTimeIso: '2026-04-12T18:00:00+01:00',
        startTime: '18:00',
        endTime: '19:30',
        tzLabel: 'GMT+1',
        title: 'TiliTalk: Women Leading Tech Innovation',
        excerpt:
            'A deep dive into the challenges and triumphs of female CTOs and tech founders in North Africa.',
        location: 'Hyatt Regency, Casablanca',
        isOnline: true,
        categoryLabel: 'TiliTalks',
        imageSrc: '/assets/talk.png',
        cta: { label: 'Register now', kind: 'primary', href: '#' },
    },
    {
        id: 'webinar-personal-branding-for-experts',
        type: 'webinar',
        badge: 'Webinar',
        dateIso: '2026-04-24',
        dateTimeIso: '2026-04-24T14:00:00+01:00',
        startTime: '14:00',
        endTime: '15:00',
        tzLabel: 'GMT+1',
        title: 'Personal Branding for Experts',
        excerpt:
            'Learn how to effectively communicate your expertise and build a strong personal brand in the digital presence.',
        location: 'Zoom',
        isOnline: true,
        categoryLabel: 'Webinars',
        imageSrc: null,
        cta: { label: 'Register', kind: 'secondary', href: '#' },
    },
    {
        id: 'workshop-speaking-with-impact',
        type: 'workshop',
        badge: 'Workshop',
        dateIso: '2026-05-05',
        dateTimeIso: '2026-05-05T08:00:00+01:00',
        startTime: '08:00',
        endTime: '13:00',
        tzLabel: 'GMT+1',
        title: 'Media Training: Speaking with Impact',
        excerpt:
            'Practical session on handling interviews, crafting soundbites, and navigating panel discussions.',
        location: '2M Studio, Casablanca',
        isOnline: false,
        categoryLabel: 'Workshops',
        imageSrc: null,
        cta: { label: 'Waitlist', kind: 'muted', href: '#' },
    },
    {
        id: 'replay-financial-inclusion-for-women-entrepreneurs',
        type: 'webinar',
        badge: 'Replay available',
        dateIso: '2025-09-28',
        dateTimeIso: '2025-09-28T16:00:00+01:00',
        startTime: '16:00',
        endTime: '17:00',
        tzLabel: 'GMT+1',
        title: 'Financial Inclusion for Women Entrepreneurs',
        excerpt:
            'Exploring funding opportunities and financial literacy strategies for entrepreneurs.',
        location: 'Webinar',
        isOnline: true,
        categoryLabel: 'Past Events / Replays',
        imageSrc: null,
        cta: { label: 'Watch replay', kind: 'ghost', href: '#' },
    },
];

