export const EXPERTS = [
    {
        id: 'sarah-amiami',
        name: 'Dr. Sarah Amiami',
        title: 'Economist & Researcher',
        tags: ['Economics', 'Finance'],
        location: 'Casablanca, MA',
        country: 'ma',
        industries: ['economics'],
        languages: ['fr', 'en', 'ar'],
        gradient: 'from-beta-green via-alpha-green/25 to-beta-blue/35',
        badge: null,
    },
    {
        id: 'yasmine-benjiloun',
        name: 'Yasmine Benjiloun',
        title: 'Tech Entrepreneur & AI Specialist',
        tags: ['Technology', 'AI'],
        location: 'Rabat, MA',
        country: 'ma',
        industries: ['technology'],
        languages: ['fr', 'en'],
        gradient: 'from-beta-yellow via-gold/25 to-beta-pink/25',
        badge: null,
    },
    {
        id: 'fatima-zahra-el-idrissi',
        name: 'Fatima Zahra El Idrissi',
        title: 'Environmental Scientist',
        tags: ['Climate', 'Sustainability'],
        location: 'Marrakesh, MA',
        country: 'ma',
        industries: ['health'],
        languages: ['fr', 'en', 'ar'],
        gradient: 'from-beta-green via-beta-blue/25 to-alpha-blue',
        badge: 'Available',
    },
    {
        id: 'khadija-oukacha',
        name: 'Khadija Oukacha',
        title: 'Human Rights Lawyer',
        tags: ['Legal', 'Human Rights'],
        location: 'Casablanca, MA',
        country: 'ma',
        industries: ['legal'],
        languages: ['fr', 'ar'],
        gradient: 'from-beta-pink via-gold/20 to-beta-yellow/30',
        badge: null,
    },
    {
        id: 'nadia-tazi',
        name: 'Nadia Tazi',
        title: 'Journalist & Author',
        tags: ['Media', 'Literature'],
        location: 'Tangier, MA',
        country: 'ma',
        industries: ['technology'],
        languages: ['fr', 'ar'],
        gradient: 'from-alpha-blue via-beta-blue/25 to-beta-green/30',
        badge: null,
    },
    {
        id: 'amira-kone',
        name: 'Dr. Amira Kone',
        title: 'Public Health Specialist',
        tags: ['Health', 'Policy'],
        location: 'Dakar, SN',
        country: 'sn',
        industries: ['health'],
        languages: ['fr', 'en'],
        gradient: 'from-beta-yellow via-beta-green/25 to-alpha-blue',
        badge: 'Available',
    },
    {
        id: 'salma-bennani',
        name: 'Salma Bennani',
        title: 'Architect / Urban Planner',
        tags: ['Urbanism', 'Design'],
        location: 'Fes, MA',
        country: 'ma',
        industries: ['economics'],
        languages: ['fr', 'ar'],
        gradient: 'from-beta-green via-alpha-blue/25 to-beta-purple/25',
        badge: null,
    },
    {
        id: 'leila-chadid',
        name: 'Leila Chadid',
        title: 'Political Analyst',
        tags: ['Politics', 'Governance'],
        location: 'Rabat, MA',
        country: 'ma',
        industries: ['legal'],
        languages: ['fr', 'en', 'ar'],
        gradient: 'from-beta-yellow via-beta-pink/25 to-gold/25',
        badge: null,
    },
];

